monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 2010
        priority.session = 2010
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
